name: "Check new groups generation with auto merge"
on:
  pull_request:

jobs:
  check-new-groups-generation-with-auto-merge:
    if: (github.actor == 'sismobot') && !contains(github.event.pull_request.title, 'ZK Badge')
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        shell: bash
        run: |
          yarn install --frozen-lockfile
      - name: Check new groups generation with auto merge
        shell: bash
        env:
          DECENTRALIZED_SUBGRAPH_API_KEY: ${{ secrets.DECENTRALIZED_SUBGRAPH_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          SH_IGNORE_RESOLVING_ERRORS: "false"
          HIVE_API_KEY: ${{ secrets.HIVE_API_KEY }}
          JSON_RPC_URL: ${{ secrets.JSON_RPC_URL }}
          TRANSPOSE_API_KEY: ${{ secrets.TRANSPOSE_API_KEY }}
          FARCASTER_API_KEY: ${{ secrets.FARCASTER_API_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          SH_GITHUB_TOKEN: ${{ secrets.SH_GITHUB_TOKEN }}
          TALLY_API_KEY: ${{ secrets.TALLY_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_BOT_SESSION: ${{ secrets.TELEGRAM_BOT_SESSION }}
          ROCI_API_KEY: ${{ secrets.ROCI_API_KEY }}
        run: |
          yarn check-new-groups-generation-with-auto-merge
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.head_ref }}
          running-workflow-name: check-new-groups-generation-with-auto-merge
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
      - name: Auto-merge
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.SISMOBOT_GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d '{"merge_method":"squash"}' https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge
