name: Update Groups Weekly staging

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * MON"
jobs:
  update:
    name: Update Groups Weekly Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set additional data as environment variable
        shell: bash
        run: |
          echo "ADDITIONAL_DATA=$(cat ${GITHUB_WORKSPACE}/scripts/additional-data.txt | tr -d "\n")" >> $GITHUB_ENV
      - name: Update groups and send on-chain
        uses: ./.github/actions/update-groups-send-on-chain
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_EXECUTION_ROLE }}
          sh-s3-data-bucket-name: "sismo-staging-hub-data"
          sh-s3-data-endpoint: "https://sismo-staging-hub-data.s3.eu-west-1.amazonaws.com"
          sh-dynamodb-global-table-name: sismo-staging-hub-global-table
          sh-default-configuration-env: staging
          sh-relay-defender-api-keys: ${{ secrets.SH_RELAY_DEFENDER_API_KEYS }}
          roots-registry-owner-mnemonic: ${{ secrets.ROOTS_REGISTRY_OWNER_MNEMONIC }}
          sh-additional-data: ${{ env.ADDITIONAL_DATA }}
          sh-generate-groups-frequency: weekly
          sh-last-generation-time-interval: "43200"
          decentralized-subgraph-api-key: ${{ secrets.DECENTRALIZED_SUBGRAPH_API_KEY }}
          google-application-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          sh-attesters: hydra-s1-accountbound
          sh-attesters-networks: goerli mumbai
          sh-registry-tree-networks: goerli
          sh-ignore-resolving-errors: "true"
          hive-api-key: ${{ secrets.HIVE_API_KEY }}
          alchemy-api-key: ${{ secrets.ALCHEMY_API_KEY }}
          json-rpc-url: ${{ secrets.JSON_RPC_URL }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          transpose-api-key: ${{ secrets.TRANSPOSE_API_KEY }}
          farcaster-api-key: ${{ secrets.FARCASTER_API_KEY }}
          dune-api-key: ${{secrets.DUNE_API_KEY}}
          gitcoin-api-key: ${{ secrets.GITCOIN_API_KEY }}
          ankr-api-key: ${{ secrets.ANKR_API_KEY }}
          github-token: ${{ secrets.SH_GITHUB_TOKEN }}
          tally-api-key: ${{ secrets.TALLY_API_KEY }}
          twitter-api-key: ${{ secrets.TWITTER_API_KEY }}
          telegram-api-hash: ${{ secrets.TELEGRAM_API_HASH }}
          telegram-api-id: ${{ secrets.TELEGRAM_API_ID }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-bot-session: ${{ secrets.TELEGRAM_BOT_SESSION }}
          roci-api-key: ${{ secrets.ROCI_API_KEY }}
